spring:
  datasource:
    url: jdbc:h2:file:./data/db
    username: sa
    password: root
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

apiPrefix: /api
host: http://localhost
server: ${host}:8080
origin: ${host}:4200